name: prodenv_alt
channels:
  - defaults
  - conda-forge
dependencies:
  - blas
  - ca-certificates
  - certifi
  - cycler
  - decorator
  - freetype
  - intel-openmp
  - joblib
  - jupyter
  - kiwisolver
  - libcxx
  - libffi
  - libgfortran
  - libpng
  - llvm-openmp
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - networkx
  - numpy
  - numpy-base
  - openssl
  - pandas
  - peakutils
  - pip
  - pyparsing
  - python
  - python-dateutil
  - pytz
  - readline
  - scikit-learn
  - setuptools
  - six
  - sqlite
  - threadpoolctl
  - tk
  - tornado
  - tqdm
  - wheel
  - xz
  - zlib
  - pip:
    - fast-pagerank==0.0.4
    - scipy==1.3.3
