name: prodenv
channels:
  - defaults
  - conda-forge
dependencies:
  - joblib
  - jupyter
  - matplotlib
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - networkx
  - numpy
  - pandas
  - peakutils
  - pip
  - python
  - scikit-learn
  - scipy
  - tqdm
  - pip:
    - fast-pagerank==0.0.4
