name: prodenv
channels:
  - defaults
  - conda-forge
dependencies:
  - joblib
  - jupyter=1.0
  - matplotlib=3.2.1
  - mkl=2019.4
  - mkl-service
  - networkx>=2.4
  - numpy>=1.17
  - pandas>=0.25
  - peakutils
  - pip
  - python=3.8
  - scikit-learn>=0.23
  - scipy>=1.3
  - tqdm>=4.46
  - pip:
    - fast-pagerank==0.0.4
